### ISSUE TITLE
Changing database

### ISSUE THREAD

**Issue by MacThanos** [victor0801x/fastify-mariadb#84]
Hi, 

Thanks for a great plugin. This might be a feature request.

Do you know how I could change the database on the fly? So on one route I might want to use one database, and another one I might use a different one.

Do I need to register the plugin again with new config options?

**Comment by victor0801x** [comment]
@MacThanos sorry for delay. I missed the notification.
I think you can specify the database in your sqlstring like `SELECT <db_name>.<table_name> xxx`.
or add a helper function to execute `USE <db_name>` query.
